export const x1 = [
    {
        id: 'TaYu_',
        name: 'Язык обложен белым налетом.',
        xPath: '4.section.text',
        code: 'C1',
        start: 847,
        end: 874,
        relativeEnd: 874,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'H7CDC',
        name: 'Селезёнка не пальпируется',
        xPath: '4.section.text',
        code: 'C1',
        start: 1001,
        end: 1026,
        relativeEnd: 1026,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'H7CDC',
        name: 'Селезёнка не пальпируется',
        xPath: '4.section.text',
        code: 'C1',
        start: 1008,
        end: 1009,
        relativeEnd: 1026,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: '2K7ws',
        name: 'клетки безболезненная. При перкуссии звук ясный легочный. При аускультации лёгких',
        xPath: '4.section.text',
        code: 'C1',
        start: 527,
        end: 608,
        relativeEnd: 1026,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
];
export const y1 = [
    {
        id: 'fDEex',
        name: 'обложен белым н',
        xPath: '4.section.text',
        code: 'C1',
        start: 852,
        end: 867,
        relativeEnd: 867,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'Jcxqi',
        name: 'Селезёнка',
        xPath: '4.section.text',
        code: 'C1',
        start: 1001,
        end: 1010,
        relativeEnd: 1010,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'Jcxqi',
        name: 'Селезёнка',
        xPath: '4.section.text',
        code: 'C1',
        start: 1001,
        end: 1011,
        relativeEnd: 1010,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: '_FcIq',
        name: 'Мочеиспускание без особенностей',
        xPath: '4.section.text',
        code: 'C1',
        start: 1127,
        end: 1158,
        relativeEnd: 1158,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
];
export const x =  [
    {
        id: 'TaYu_',
        name: 'Язык обложен белым налетом.',
        xPath: '4.section.text',
        code: 'C1',
        start: 847,
        end: 874,
        relativeEnd: 874,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'fDEex',
        name: 'обложен белым н',
        xPath: '4.section.text',
        code: 'C1',
        start: 852,
        end: 867,
        relativeEnd: 867,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'HKpaO',
        name: 'Селезёнка не пальпируется.',
        xPath: '4.section.text',
        code: 'C1',
        start: 1001,
        end: 1027,
        relativeEnd: 1027,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'H7CDC',
        name: 'Селезёнка не пальпируется',
        xPath: '4.section.text',
        code: 'C1',
        start: 1001,
        end: 1026,
        relativeEnd: 1026,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'Jcxqi',
        name: 'Селезёнка',
        xPath: '4.section.text',
        code: 'C1',
        start: 1001,
        end: 1010,
        relativeEnd: 1010,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: '_FcIq',
        name: 'Мочеиспускание без особенностей',
        xPath: '4.section.text',
        code: 'C1',
        start: 1127,
        end: 1158,
        relativeEnd: 1158,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'JQRfU',
        name: 'Рост 176 см.Вес 103,0 кг.ИМТ 33,25 кг/м2. В сознании. Во времени и пространстве ориентирован. Телосложение гиперстеническое. Температура тела 36,8С. Подкожно - жировая клетчатка развита избыточно. Кожные покровы физиологической окраски. Костно - мышечная система без особенностей. Визуально суставы кистей не изменены, не отечны, объём движений в них не ограничен. Лимфоузлы при пальпации не увеличены. Щитовидная железа не увеличена. Вспомогательная мускулатура в дыхании не участвует. ЧДД 16 в мин в покое. Пальпация грудной клетки безболезненная. При перкуссии звук ясный легочный. При аускультации лёгких дыхание везикулярное, хрипов нет. При осмотре пульсация сонных артерий не определяется . Вены шеи не изменены, не пульсируют. При аускультации сердечные тоны ясные, ритм не нарушен. ЧСС 82в минуту, пульс 82в минуту. АД 125 /85 мм рт. ст. Язык обложен белым налетом. Живот мягкий, болезненный при пальпации в эпигастральной области. Печень не увеличена. Размеры печени по Курлову - 9 х 8 х 7. Селезёнка не пальпируется. Стул нарушен: до 5 раз в день кашицеобразный. Симптом поколачивания отрицательный с обеих сторон . Мочеиспускание без особенностей. Больной в сознании, ориентирован во времени и собственной личности. Контакту доступен.',
        xPath: '4.section.text',
        code: 'C1',
        start: 0,
        end: 1246,
        relativeEnd: 1246,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: 'maPDM',
        name: 'Пальпация грудной клетки безболезненная.',
        xPath: '4.section.text',
        start: 509,
        end: 549,
        relativeEnd: 549,
        status: 'selected',
        hidden: false,
    },
    {
        id: 'BkvYj',
        name: 'Щитовидная железа не увеличена. Вспомогательная мускулатура в дыхании не участвует. ЧДД 16 в мин в покое. Пальпация грудной клетки',
        xPath: '4.section.text',
        code: 'C1',
        start: 403,
        end: 533,
        relativeEnd: 533,
        status: 'done',
        decorCode: 'diagnosisMain',
        hidden: false,
    },
    {
        id: '2K7ws',
        name: 'клетки безболезненная. При перкуссии звук ясный легочный. При аускультации лёгких',
        xPath: '4.section.text',
        start: 527,
        end: 608,
        relativeEnd: 608,
        status: 'selected',
        hidden: false,
    },
];